<h1>Books</h1>


<div class='row'>
    <?php foreach ($books as $book) : ?>
        <div class='col-md-4'>
            <div class="card" style="min-height: 200px; margin-top: 10px">
              <!--<img class="card-img-top" src="..." alt="Card image cap">-->
              <div class="card-body">
                <h4 class="card-title"><?=$book->getTitle() ?></h4>
                <p class="card-text"><?=$book->getPrice() ?></p>
                  <p class="card-text"><?=$book->getShortDescription()?></p>
                <a href="#" class="btn btn-primary">Add to cart</a>
                <a href="/index.php?controller=book&amp;action=show&amp;id=<?=$book->getId() ?>" class="btn btn-success">Details</a>
              </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div style="margin-top: 100px" class="container">
<div class="row">
<?php for($i=1;$i<=$pages;$i++):?>
    <a href="/index.php?controller=book&action=index&page=<?=$i?>"><?=$i?></a>
<?php endfor;?>
</div>
</ul>
</div>
